### ISSUE TITLE
output file size of similarities.txt inconsistent

### ISSUE THREAD

**Issue by Nostimo** [seinecle/MapsOfScience#2]
I'm getting a different file sizes for similarities.txt on each run. This seems to be caused by the method doubleLoopingThroughJournalIds() which is not waiting for all the tasks in the ExecutorService to finish.

**Comment by seinecle** [comment]
Hi, thanks for the feedback! Is the file size different by just a few lines? If so, that would mean that a few last similarity computations are performed but not written to disk?

I just added this loop to make sure the queue is empty before we stop writing to disk:

```
        while (!queue.isEmpty()){
            Thread.sleep(100);
        }
        queueProcessor.stop();
```

Or is it something else?

**Comment by Speiger** [comment]
@seinecle this is actually solved by using this:
```java
 // Requests a shutdown and will no longer accept any new tasks, but already inserted tasks will be completed
 // But that is fine since the stream is completed before it will continue in the code.
executor.shutdown();

 //Awaits either 10 minutes or if all tasks are completed. Whatever is first. I don't know whats a reasonable await time.
executor.awaitTermination(10L, TimeUnit.MINUTES);
queueProcessor.stop();
```

**Comment by seinecle** [comment]
thanks!! I added this.
